###
# GET A STUDENTS DETAILS
GET http://localhost:3000/api/student/1/details
###

###
# GET A TEACHERS DETAILS
GET http://localhost:3000/api/teacher/1/details
###

###
# GET A STUDENTS LEVEL
GET http://localhost:3000/api/student/1/level
###

###
# GET A STUDENTS HOME LANGUAGE
GET http://localhost:3000/api/student/1/language
###

###
# GET A FLASHCARD
GET http://localhost:3000/api/flashcard/1
###

###
# SEE FLASHCARDS FOR A LANGUAGE AND LEVEL
GET http://localhost:3000/api/flashcard/7/French
###

###
# SEE FLASHCARDS DUE
GET http://localhost:3000/api/flashcard/due/1
###

###
# SEE USER FLASHCARDS DUE
GET http://localhost:3000/api/flashcard/usercards/due/1
###

###
# MARK A FLASHCARD AS REVIEWED
POST http://localhost:3000/api/flashcard/5/review
Content-Type: application/json

{
  "user_id": 1,
  "reviewResult": "Good"
}
###

###
# MARK A FLASHCARD AS REVIEWED THAT THEY HAVEN'T REVIEWED BEFORE
POST http://localhost:3000/api/flashcard/3/review
Content-Type: application/json

{
  "user_id": 3,
  "reviewResult": "Good"
}
###

###
# MARK A USER FLASHCARD AS REVIEWED
POST http://localhost:3000/api/flashcard/usercards/3/review
Content-Type: application/json

{
  "user_id": 4,
  "reviewResult": "Good"
}
###

###
# CREATE A FLASHCARD
POST http://localhost:3000/api/flashcard/create
Content-Type: application/json

{
  "user_id": 1,
  "type": "Normal",
  "title": "Test creation",
  "front": "Test front",
  "back": "Test back"
}
###

###
# CREATE AN AI FLASHCARD
POST http://localhost:3000/api/flashcard/usercards/prompt/1
Content-Type: application/json

{
  "cardCount": 4
}
###


###
# CREATE A NEW STUDENT
POST http://localhost:3000/api/student
Content-Type: application/json

{
  "username": "new_student",
  "password": "123456",
  "email": "new_student@email.com",
  "role": "student",
  "student_home_language": "English"
}
###

###
# CREATE A NEW TEACHER
POST http://localhost:3000/api/teacher
Content-Type: application/json

{
  "username": "new_teacher",
  "password": "123456",
  "email": "new_teacher@email.com",
  "role": "teacher",
  "teacher_home_language": "English",
  "qualifications": "Masters in English Literature",
  "teacher_biography": "I have been teaching English for over 10 years.",
  "teacher_profile_image": "https://avatars.githubusercontent.com/u/2827932?v=4"
}
###

###
# UPDATE A TEACHER'S DETAILS
PUT http://localhost:3000/api/teacher/1/update
Content-Type: application/json

{
  "teacher_name": "updated_teacher",
  "teacher_profile_image": "https://avatars.githubusercontent.com/u/2827932?v=4",
  "teacher_biography": "Updated biography, I have now been teaching for 15 years",
  "qualifications": "Updated qualifications, now a PhD in English Literature"
}
###
