export {default as flashCard} from './flashCard';
export {default as homePage} from './homePage';
export {default as messagePage} from './messagePage';
export {default as register} from './register';
export {default as registerHome} from './registerHome'
export {default as studentPage} from './studentPage'
export {default as teacherPage} from './teacherPage';
export {default as login} from './login';
export {default as about} from './about';
