export {default as flashCard} from './flashCard';
export {default as homePage} from './homePage';
export {default as messagePage} from './messagePage';
export {default as register} from './register';
export {default as registerHome} from './registerHome';export {default as registerTeacher} from './register';
export {default as studentPage} from './studentPage';
export {default as teacherPage} from './teacherPage';
export {default as login} from './login';
export {default as userFlashcardReview} from './userFlashcardReview';
export {default as about} from './about';
export {default as createFlashCard} from './createFlashCard';
export {default as updateProfileTeacher} from './updateProfileTeacher';
export {default as teacherProfile} from './teacherProfile';
